import { useState } from "react";
import { TotalAnimalsContext } from "./all.context";

const ANIMALS = [
  {
    animalName: "Leo",
    healthStatus: "excellent",
    age: 5,
    weight: 190,
    enclosure: "Savannah Zone A",
    lastCheckup: "2025-07-10",
    diet: "Carnivore - Beef & Chicken",
    notes: "Very active during mornings",
    animalImage: "",
    species: "Lion",
    category: "Mammal",
  },
  {
    animalName: "Ella",
    healthStatus: "poor",
    age: 12,
    weight: 5400,
    enclosure: "Elephant Habitat B",
    lastCheckup: "2025-06-28",
    diet: "Herbivore - Grass & Fruits",
    notes: "Left tusk chipped",
    animalImage: "",
    species: "Elephant",
    category: "Mammal",
  },
  {
    animalName: "Stripes",
    healthStatus: "excellent",
    age: 7,
    weight: 220,
    enclosure: "Jungle Zone C",
    lastCheckup: "2025-07-15",
    diet: "Carnivore - Goat Meat",
    notes: "Territorial, keep isolated",
    animalImage: "",
    species: "Tiger",
    category: "Mammal",
  },
  {
    animalName: "Kiki",
    healthStatus: "critical",
    age: 3,
    weight: 12,
    enclosure: "Monkey Island",
    lastCheckup: "2025-07-30",
    diet: "Fruits, Nuts, Insects",
    notes: "Behavioral changes noticed",
    animalImage: "",
    species: "Capuchin Monkey",
    category: "Mammal",
  },
  {
    animalName: "Shelly",
    healthStatus: "excellent",
    age: 80,
    weight: 200,
    enclosure: "Reptile House",
    lastCheckup: "2025-07-05",
    diet: "Herbivore - Lettuce, Grass",
    notes: "Slow movement but normal",
    animalImage: "",
    species: "Giant Tortoise",
    category: "Reptile",
  },
  {
    animalName: "Flare",
    healthStatus: "excellent",
    age: 4,
    weight: 1.5,
    enclosure: "Aviary Zone",
    lastCheckup: "2025-08-01",
    diet: "Seeds & Insects",
    notes: "Bright red feathers",
    animalImage: "",
    species: "Macaw",
    category: "Bird",
  },
  {
    animalName: "Rocky",
    healthStatus: "fair",
    age: 9,
    weight: 350,
    enclosure: "Bear Den",
    lastCheckup: "2025-07-22",
    diet: "Fish, Berries, Honey",
    notes: "Recovered from leg fracture",
    animalImage: "",
    species: "Brown Bear",
    category: "Mammal",
  },
  {
    animalName: "Dash",
    healthStatus: "excellent",
    age: 6,
    weight: 40,
    enclosure: "Savannah Zone B",
    lastCheckup: "2025-07-19",
    diet: "Carnivore - Small Prey",
    notes: "Fast runner, very agile",
    animalImage: "",
    species: "Cheetah",
    category: "Mammal",
  },
  {
    animalName: "Polly",
    healthStatus: "excellent",
    age: 15,
    weight: 25,
    enclosure: "Penguin Pool",
    lastCheckup: "2025-08-05",
    diet: "Fish & Squid",
    notes: "Enjoys swimming in groups",
    animalImage: "",
    species: "Penguin",
    category: "Bird",
  },
  {
    animalName: "Bubbles",
    healthStatus: "excellent",
    age: 20,
    weight: 300,
    enclosure: "Aquatic Zone",
    lastCheckup: "2025-07-25",
    diet: "Fish & Crustaceans",
    notes: "Friendly with trainers",
    animalImage: "",
    species: "Dolphin",
    category: "Aquatic",
  },
  {
    animalName: "Nala",
    healthStatus: "good",
    age: 8,
    weight: 160,
    enclosure: "Lioness Den",
    lastCheckup: "2025-07-18",
    diet: "Carnivore - Beef",
    notes: "Expected to deliver in 2 months",
    animalImage: "",
    species: "Lioness",
    category: "Mammal",
  },
  {
    animalName: "Spike",
    healthStatus: "excellent",
    age: 11,
    weight: 800,
    enclosure: "Rhino Enclosure",
    lastCheckup: "2025-07-20",
    diet: "Herbivore - Grass",
    notes: "Aggressive when approached",
    animalImage: "",
    species: "Rhinoceros",
    category: "Mammal",
  },
  {
    animalName: "Slither",
    healthStatus: "excellent",
    age: 5,
    weight: 25,
    enclosure: "Snake House",
    lastCheckup: "2025-07-12",
    diet: "Carnivore - Rodents",
    notes: "Shed skin recently",
    animalImage: "",
    species: "Python",
    category: "Reptile",
  },
  {
    animalName: "Gracy",
    healthStatus: "excellent",
    age: 14,
    weight: 700,
    enclosure: "Giraffe Enclosure",
    lastCheckup: "2025-07-27",
    diet: "Herbivore - Leaves",
    notes: "Neck injury healed",
    animalImage: "",
    species: "Giraffe",
    category: "Mammal",
  },
  {
    animalName: "Fang",
    healthStatus: "fair",
    age: 6,
    weight: 120,
    enclosure: "Wolf Pack Zone",
    lastCheckup: "2025-07-31",
    diet: "Carnivore - Meat",
    notes: "Needs improved diet plan",
    animalImage: "",
    species: "Wolf",
    category: "Mammal",
  },
];

function TotalAnimalsProvider({ children }) {
  const [animalList, setAnimalList] = useState(ANIMALS);
  return (
    <TotalAnimalsContext.Provider value={{ animalList, setAnimalList }}>
      {children}
    </TotalAnimalsContext.Provider>
  );
}
export default TotalAnimalsProvider;
